export const NOTIFICATION_TYPE_AUTO_REMOVABLE = 'autoRemovable';
export const NOTIFICATION_TYPE_NON_REMOVABLE = 'nonRemovable';
export const NOTIFICATION_TYPE_REMOVABLE = 'removable';

export const NOTIFICATION_VARIANT_ERROR = 'error';
export const NOTIFICATION_VARIANT_INFO = 'info';
export const NOTIFICATION_VARIANT_SUCCESS = 'success';
export const NOTIFICATION_VARIANT_WARNING = 'warning';

export const NOTIFICATION_TYPES = [
  NOTIFICATION_TYPE_AUTO_REMOVABLE,
  NOTIFICATION_TYPE_NON_REMOVABLE,
  NOTIFICATION_TYPE_REMOVABLE,
];

export const NOTIFICATION_VARIANTS = [
  NOTIFICATION_VARIANT_ERROR,
  NOTIFICATION_VARIANT_INFO,
  NOTIFICATION_VARIANT_SUCCESS,
  NOTIFICATION_VARIANT_WARNING,
];
